server:
  port: 9000

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/login?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey: z1gWDQyOzFEV7pv5PIMhauPQen4cbXVBG8sM1SfKT6FrXm8FPnRdLUrRJqMGF4cWPMjna9mOxzAfup9SCX6QZKZikBf4iIYjevI7
  expires:
    accessToken: 600      # 10? (10 * 60?)
    refreshToken: 3600    # 1?? (60 * 60?)